WITH 
  MY_TEMP_1 AS (     
    SELECT DISTINCT THANG AS month, ID_KH as client_id,   
    (CASE 
    WHEN nhom_thang_N like 'A%' then 'A'
    WHEN nhom_thang_N in ('B', 'C', 'D') then 'BCD'
    WHEN nhom_thang_N in ('E', 'F') then 'EF'
    ELSE null
    END
    ) as customer_rank,
    (CASE 
    WHEN nhom_thang_N like 'A%' then 4
    WHEN nhom_thang_N in ('B', 'C', 'D') then 3
    WHEN nhom_thang_N in ('E', 'F') then 2
    ELSE NULL
    END
    ) AS customer_rank_in_num 
    FROM ad_hoc.phan_nhom_kh_crm_v2
    WHERE THANG <  '2023-01-01'
    AND (nhom_thang_N like 'A%' or nhom_thang_N in ('B', 'C', 'D'))
  ),

  MY_TEMP_2 AS (
    SELECT DISTINCT Dot as month, client_id,
    (CASE 
    WHEN nhom_KH like 'A%' then 'A'
    WHEN nhom_KH in ('B', 'C', 'D') then 'BCD'
    WHEN nhom_KH in ('E', 'F') then 'EF'
    ELSE null
    END
    ) as customer_rank,
    (CASE 
    WHEN nhom_KH like 'A%' then 4
    WHEN nhom_KH in ('B', 'C', 'D') then 3
    WHEN nhom_KH in ('E', 'F') then 2
    ELSE NULL
    END
    ) AS customer_rank_in_num
    
    FROM `ad_hoc.IDKH_PercentageRevenue`
    where (nhom_KH like 'A%' or nhom_KH in ('B', 'C', 'D'))
  ),

  MY_TEMP_MERGE AS (
    SELECT * FROM MY_TEMP_1
    UNION ALL
    SELECT * FROM MY_TEMP_2
  ),

  FIRST_MONTH_TABLE AS (
    SELECT CLIENT_ID, MIN(MONTH) AS FIRST_MONTH FROM MY_TEMP_MERGE
    GROUP BY CLIENT_ID
  ),

  TABLE_CRM_1 AS(
    SELECT L.*, 
    R.FIRST_MONTH
    FROM MY_TEMP_MERGE AS L #NO EF IN 2022
    LEFT JOIN FIRST_MONTH_TABLE AS R
    ON L.client_id = R.client_id
  ),
  TABLE_CRM_2 AS (
    SELECT L.MONTH, L.CLIENT_ID, L.CUSTOMER_RANK, L.CUSTOMER_RANK_IN_NUM, 
    R.MONTH AS PREVIOUS_MONTH, R.CUSTOMER_RANK AS PREVIOUS_RANK
    FROM TABLE_CRM_1 AS L
    LEFT JOIN TABLE_CRM_1 AS R
    ON L.CLIENT_ID = R.CLIENT_ID
    AND L.MONTH > R.MONTH
    ORDER BY L.CLIENT_ID

  ),
  TABLE_CRM_3 AS (
    SELECT MONTH, CLIENT_ID, 
    CUSTOMER_RANK, CUSTOMER_RANK_IN_NUM,
    DATE_DIFF(MONTH, MAX(PREVIOUS_MONTH), MONTH) AS INTERVAL_ABCD 
    FROM TABLE_CRM_2
    GROUP BY MONTH, CLIENT_ID, CUSTOMER_RANK, CUSTOMER_RANK_IN_NUM 
  ),
  TABLE_CRM_4 AS (
    SELECT *, (CASE WHEN INTERVAL_ABCD <= 12 THEN 0 ELSE 1 END) AS IS_NEW_CUSTOMER #NEW CUSTOMER DURATION
    FROM TABLE_CRM_3
    ORDER BY INTERVAL_ABCD ASC
  ),
  
  TABLE_CRM_MAIN AS (
    SELECT L.MONTH AS CURRENT_MONTH, L.CLIENT_ID, L.CUSTOMER_RANK, L.CUSTOMER_RANK_IN_NUM,
    R.MONTH, R.CUSTOMER_RANK AS NEXT_MONTH_RANK, R.CUSTOMER_RANK_IN_NUM AS NEXT_MONTH_RANK_IN_NUM, 
    DATE_DIFF(R.MONTH, L.MONTH, MONTH) AS MONTH_INTERVAL,
    
    (CASE WHEN L.CUSTOMER_RANK_IN_NUM - R.CUSTOMER_RANK_IN_NUM IS NULL THEN 0 ELSE 1 END) AS IS_RETENTION 
    FROM TABLE_CRM_4 AS L
    LEFT JOIN TABLE_CRM_1 AS R
    ON L.CLIENT_ID = R.CLIENT_ID
    AND L.MONTH <= R.MONTH
    WHERE IS_NEW_CUSTOMER = 1
  ),
  COHORT_TABLE AS (
    SELECT CURRENT_MONTH, CUSTOMER_RANK, MONTH_INTERVAL, SUM(IS_RETENTION) as RETENTION_C2 FROM TABLE_CRM_MAIN
    GROUP BY CURRENT_MONTH,  CUSTOMER_RANK, MONTH_INTERVAL
    ORDER BY CURRENT_MONTH, CUSTOMER_RANK, MONTH_INTERVAL  
  )


SELECT L.*, R.RETENTION_C2 AS TOTAL_NEW_CUSTOMERS
FROM COHORT_TABLE AS L
LEFT JOIN (SELECT * FROM COHORT_TABLE WHERE MONTH_INTERVAL = 0) AS R
ON L.CURRENT_MONTH = R.CURRENT_MONTH
AND L.CUSTOMER_RANK = R.CUSTOMER_RANK
ORDER BY L.CURRENT_MONTH ASC, CUSTOMER_RANK ASC, MONTH_INTERVAL ASC









